title: "I ♥ DS"
description: "Personal thoughts, ideas, and writing."
baseurl: ""
url: "https://imscientist.dev"

theme: minima
permalink: pretty

author:
  name: "ImScientist"
  bio: ""
  profile_image: /assets/images/me.jpeg
  linkedin: "https://www.linkedin.com/in/imscientist"
  github: "https://github.com/ImScientist"

plugins:
  - jekyll-feed
  - jekyll-seo-tag

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - vendor/
